/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFridayReplyRouteImport } from './routes/api/friday/reply'
import { Route as ApiFridayTranscribeRouteImport } from './routes/api/friday/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFridayReplyRoute = ApiFridayReplyRouteImport.update({
  id: '/api/friday/reply',
  path: '/api/friday/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFridayTranscribeRoute = ApiFridayTranscribeRouteImport.update({
  id: '/api/friday/transcribe',
  path: '/api/friday/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/friday/reply': typeof ApiFridayReplyRoute
  '/api/friday/transcribe': typeof ApiFridayTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/friday/reply': typeof ApiFridayReplyRoute
  '/api/friday/transcribe': typeof ApiFridayTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/friday/reply': typeof ApiFridayReplyRoute
  '/api/friday/transcribe': typeof ApiFridayTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/friday/reply' | '/api/friday/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/friday/reply' | '/api/friday/transcribe'
  id: '__root__' | '/' | '/api/friday/reply' | '/api/friday/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFridayReplyRoute: typeof ApiFridayReplyRoute
  ApiFridayTranscribeRoute: typeof ApiFridayTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friday/reply': {
      id: '/api/friday/reply'
      path: '/api/friday/reply'
      fullPath: '/api/friday/reply'
      preLoaderRoute: typeof ApiFridayReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friday/transcribe': {
      id: '/api/friday/transcribe'
      path: '/api/friday/transcribe'
      fullPath: '/api/friday/transcribe'
      preLoaderRoute: typeof ApiFridayTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFridayReplyRoute: ApiFridayReplyRoute,
  ApiFridayTranscribeRoute: ApiFridayTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
